import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* So whenever we use server rendering, normally there is a warning when server and the client render different content well that's what we're going to get with next themes */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased transition-all duration-500 dark:bg-[#0A0A0A] light:bg-[#FFFFFF] light:text-[#000]`}
      >
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
